project: Chatlio.xcodeproj
schemes:
- Chatlio
- UnitTests
- PreviewTests
- UITests
- IntegrationTests
targets:
- Chatlio
- NSE
- ShareExtension
- UnitTests
- PreviewTests
- UITests
- IntegrationTests
report_exclude:
  - Chatlio/Sources/Mocks/Generated/GeneratedMocks.swift
  - Chatlio/Sources/Mocks/Generated/SDKGeneratedMocks.swift
retain_swift_ui_previews: true
