sources:
  include:
    - ../../Chatlio
    - ../../NSE
  exclude:
    - ../../Chatlio/Sources/Mocks/SDK
templates:
  - AutoMockable.stencil
output:
  ../../Chatlio/Sources/Mocks/Generated/GeneratedMocks.swift
